services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot-backend
    ports:
      - "10000:10000"
    env_file:
      - .env
    environment:
      PYTHONPATH: /app

  frontend:
    build:
      context: ./frontend/full_page_frontend
      dockerfile: Dockerfile
    container_name: chatbot-frontend
    ports:
      - "8080:8080"
